# Week 5 Exercises

## Ex 1: Break Points and Growth Functions 

-   Is there always a break point for a finite hypothesis set of $n$
    hypotheses? If so, can you give a an upper bound? What is the growth
    function?

-   Does the set of all functions have a break point? What is its growth
    function?

-   What is the (smallest) break point for the hypothesis set consisting
    of circles centered around $(0,0)$? For a given circle the
    hypothesis returns $1$ for points inside the circle and $-1$ for
    points outside. What is the growth function?

-   What if we move to centered balls in the 3-dimensional space
    ${{\mathbb R}}^3$? Or in general $d$-dimensional space
    ${{\mathbb R}}^d$ (hyperspheres)?

-  Show that the growth function for a singleton hypothesis class $H = \{h\}$ is 1


### SOLUTION MATH
1. Since we have $n$ hypotheses, the growth function is capped at $n$. Therefore it must have a break point of at most $\lfloor \lg n \rfloor + 1$.

2. It does not have a break point. Its growth function is $m(n)=2^n$ since all functions can create all dichotomies.

3. The break point is at 2 since for two points of distinct distances, it is impossible to construct the dichotomy having $1$ on the point furthest from the origin and $-1$ on the point closest. If 2 points have the same distance, then any dichotomy with two distinct labels is impossible. The growth function is the same as positive rays in 1d (sort by distances), hence $m(n)=1+n$.

4. The same since all that matters is the distance to the origin.

5. Regardless of the number of points $x_1,\dots,x_k$, there is only one dichotomy generated by $H$. So the growth function is $m_H(k)=1$ for all $k$.

### END SOLUTION

## Ex 2: VC Dimension 

-   Does VC Dimension depend on the learning algorithm or the actual
    data set given?

-   Does VC Dimension depend on the probability distribution generating
    the data (not the labels)?

-   If $\mathcal{H}_1 \subseteq \mathcal{H}_2$ is
    $VC(\mathcal{H}_1) \leq VC(\mathcal{H}_2)?$

-   Can you give an upper bound on the VC dimension of a finite set of
    $M$ hypotheses?

-   What is the VC Dimension for the hypothesis set consisting of
    circles centered around 0?

-   What if we move to balls (3d)? or in general d dimensions
    (hyperspheres)?

-   What is the maximal VC dimension possible of the intersection of
    hypothesis sets $\mathcal{H}_1,\dots,\mathcal{H}_n$ with VC
    dimension $v_1,\dots,v_n$.

-   As previous question, instead what is the minimal VC dimension of
    the union of the hypothesis sets from the previous question

-   Show that the VC dimension of the hypothesis set consisting of axis aligned rectangles in $\mathbb{R}^2$ is 4,
    i.e. find a point set of 4 points you can shatter and argue that any point set of size 5 can not.
    

### SOLUTION MATH
1. No
2. No
3. yes. If you can shatter a point set using $\mathcal{H}_1$, you can use the same hypotheses to shatter it using $\mathcal{H}_2$ since $\mathcal{H}_1 \subseteq \mathcal{H}_2$.
4. yes, $\lfloor log M \rfloor$. To see this, notice that for VC dimension $d$, one must be able to shatter a set of $d$ points, i.e. $M \geq 2^d$.
5. same as positive rays in 1d, namely 1. sort by distance -1 +1 is impossible.
6. The same
7. The minimum of the VC dimensions since the intersection is contained in all.
8. The largest of the VC dimensions since you always keep at least the largest and all others might be subset of it.
9. To prove at least 4, pick points (0,1), (0,-1), (1,0), (-1,0). Not hard to see that all dichotomies can be obtained. To prove less than 5, consider any set of 5 points in the plane. Let $B$ be their bounding box. All the 5 points are contained in $B$, and to construct the "full" dichotomy, one must use a rectangle containing at least $B$. Now consider the dichotomy that contains all points on the boundary of the bounding box but none of the points inside. That dichotomy is impossible if the box $B$ has a point in its interior. Finally, if all 5 points lie on the boundary of the bounding box, there are two that lie on the same side of the bounding box. Any dichotomy involving all but one of those two is impossible.
### END SOLUTION

## Ex 3:  Book Exercise
### Exercise 1.11 in the [LFD] Book 
(Not problem, but exercise inside the text. page 25) <b>Hint:</b> For (c), you may either compute it exactly, or use Hoeffding's inequality to get an approximation.


### SOLUTION MATH
a. No. The training data might be such that it contains most examples with the most unlikely label.

b. Yes. It might be the case that $p$ is very small, say 0.1, and yet the sample has only points with label +1.

c. It equals the probability that $B(n,0.9)>n/2$ where $n=25$. 

If we want to be exact, we get that the probability is $\sum_{i=13}^{25} 0.9^i 0.1^{25-i} \binom{25}{i}$.

For a simpler, but inexact solution, we can e.g. use Hoeffding to get a bound on this. Let $X \sim B(25,0.9)/25$. We see that $\Pr[X < 0.5] \leq \Pr[|X-0.9|>0.4] \leq 2\exp(-2 \cdot 0.4^2 \cdot 25) < 0.00068$. Hence $S$ produces a better hypothesis with probability at least $1-0.00068$.


d. No as $S$ outputs the maximum likelihood estimate. In more detail, assume wlog. $p \geq 1/2$, then S produces the best hypothesis with probability $\sum_{i=13}^{25} p^i (1-p)^{25-i} \binom{25}{i}$ and C produces it with probability $\sum_{i=13}^{25} (1-p)^i p^{25-i} \binom{25}{i}$. Look at the ratio between two terms in the sum: $p^i (1-p)^{25-i} \binom{25}{i}/(1-p)^i p^{25-i} \binom{25}{i} = (p/(1-p))^i ((1-p)/p)^{25-i} = (p/(1-p))^{2i-25}$. Since $2i>25$ for every $i$ in the sum and $p/(1-p) \geq 1$, we see that the first probability is larger.

### END SOLUTION

## Ex 4: Regularization with Weight decay
If we use weight decay regularization ($\lambda||w||^2)$  for some real number $\lambda$ in Linear Regression, what 
happens to the optimal weight vector if we let $\lambda \rightarrow \infty$? (cost is $\frac{1}{n} \|Xw - y\|^2 + \lambda \|w\|^2$)

## SOLUTION MATH

If we let $\lambda \rightarrow \infty$, then the best choice of $w$ is $0$ as the cost of this solution tends to $\frac{1}{n}\|y\|^2$ whereas the cost of all other $w'$ tend to infinity.

### END SOLUTION

## Ex 5: Grid Search For Regularization and Validation - Sklearn
In this exercise we will optimize a [Decision Tree Classifier](http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html) using regularization and validation.
You must use the grid search module [GridSearchCV](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV) from sklearn.

In the cell below we have shown an example of how to use the grid search module to test two different values for max_depth for a decision tree for wine classification

Your job is to find good hyperparameters for decision trees for breast cancer detection.

### Task 1:
For the breast cancer data set, find the best (or very good) combination of max_depth and min_samples_split (cell two below)

The **max_depth** parameter controls the max depth of a tree and the deeper the tree the more complex the model.

The **min_samples_split** controls how many elements the algorithm that constructs the tree is allowed to try and split.
So if a subtree contains less than min_leaf_size elements, it may not be split into a larger subtree by the algorithm.


### Task 2:
- How long time does it take to use grid search validation for $k$ hyperparameters where we test each parameter for $d$ values, and the training algorithm uses $f(n)$ time to train on $n$ data points when we split the data into 5 parts.


### SOLUTION MATH

For task 2: There are $d^k$ combinations of hyperparameters to test. For each, we train $5$ times on $(4/5)n$ points. So the total running time is $d^k 5 f((4/5)n) = O(d^k f((4/5)n))$. For non-decreasing $f$, this is bounded by $O(d^k f(n))$.

### END SOLUTION

In [1]:
from sklearn.datasets import load_wine, load_breast_cancer
import numpy as np
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier


from sklearn.datasets import fetch_covtype

def show_result(clf):
    df = pd.DataFrame(clf.cv_results_)
    df = df.sort_values('mean_test_score', ascending=False)
    display(df)
    print('best parameter found', clf.best_params_)
    
w_data = load_wine()
wine_data = w_data.data
wine_labels = w_data.target

# grid search validation
reg_parameters = {'max_depth': [1, 30]}  # dict with all parameters we need to test
clf = GridSearchCV(DecisionTreeClassifier(), reg_parameters, cv=3, return_train_score=True)
clf.fit(wine_data, wine_labels)
# code for showing the result
bt = show_result(clf)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,mean_train_score,std_train_score
1,0.000892,0.000077,0.000296,0.00002,30,{'max_depth': 30},0.950000,0.830508,0.932203,0.904237,0.052638,1,1.000000,1.000000,1.000000,1.00000,0.000000
0,0.000840,0.000285,0.000323,0.00004,1,{'max_depth': 1},0.566667,0.576271,0.711864,0.618267,0.066299,2,0.677966,0.672269,0.689076,0.67977,0.006979

best parameter found {'max_depth': 30}

In [2]:
cancer_data = load_breast_cancer()
c_data = cancer_data.data
c_labels = cancer_data.target


def decisiontree_model_selection(train_data, labels):
    clf = None
    ### YOUR CODE HERE
    reg_parameters = {'max_depth': [5, 10, 15],
                      'min_samples_split': [2, 5, 10]}                
    clf = GridSearchCV(DecisionTreeClassifier(), reg_parameters, cv=5, return_train_score=True)
    clf.fit(train_data, labels)
    ### END CODE
    return clf
###
clf = decisiontree_model_selection(c_data, c_labels)
bt = show_result(clf)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
1,0.005056,0.000314,0.000223,8.926471e-05,5,5,"{'max_depth': 5, 'min_samples_split': 5}",0.912281,0.938596,0.921053,...,0.927915,0.017156,1,0.993407,0.993407,0.989011,0.986813,0.991228,0.990773,0.002564
0,0.006138,0.001483,0.000324,1.247412e-04,5,2,"{'max_depth': 5, 'min_samples_split': 2}",0.912281,0.938596,0.929825,...,0.924375,0.019191,2,0.993407,0.995604,0.991209,0.986813,0.991228,0.991652,0.002915
2,0.004271,0.000260,0.000155,6.529362e-06,5,10,"{'max_depth': 5, 'min_samples_split': 10}",0.903509,0.938596,0.929825,...,0.922652,0.013022,3,0.991209,0.993407,0.984615,0.980220,0.991228,0.988136,0.004936
3,0.004838,0.000487,0.000175,2.876581e-05,10,2,"{'max_depth': 10, 'min_samples_split': 2}",0.912281,0.912281,0.921053,...,0.920882,0.018565,4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
8,0.006095,0.000672,0.000161,1.538833e-05,15,10,"{'max_depth': 15, 'min_samples_split': 10}",0.912281,0.912281,0.929825,...,0.920882,0.015885,4,0.995604,0.982418,0.993407,0.984615,0.997807,0.990770,0.006123
7,0.006113,0.000620,0.000157,3.479931e-06,15,5,"{'max_depth': 15, 'min_samples_split': 5}",0.912281,0.903509,0.912281,...,0.915603,0.021386,6,0.997802,0.993407,0.997802,0.997802,0.997807,0.996924,0.001759
6,0.005624,0.001160,0.000199,6.171783e-05,15,2,"{'max_depth': 15, 'min_samples_split': 2}",0.903509,0.921053,0.929825,...,0.915588,0.019215,7,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
4,0.004808,0.000516,0.000154,2.908316e-06,10,5,"{'max_depth': 10, 'min_samples_split': 5}",0.912281,0.912281,0.912281,...,0.915588,0.022872,8,0.997802,0.993407,0.997802,0.997802,0.997807,0.996924,0.001759
5,0.004787,0.000508,0.000150,4.672031e-07,10,10,"{'max_depth': 10, 'min_samples_split': 10}",0.903509,0.903509,0.929825,...,0.912079,0.019497,9,0.995604,0.982418,0.993407,0.984615,0.997807,0.990770,0.006123

best parameter found {'max_depth': 5, 'min_samples_split': 5}

## Ex 6: VC Dimension of Hyperplanes (Book Exercise 2.4 p. 52)
Consider the input space $\mathcal{X} = \{1\} \times \mathbb{R}^d$ (with the first coordinate being the constant 1). Show that the VC dimension of the hypothesis space $\mathcal{H} = \{\textrm{sign}(w^\intercal x) \mid w\in \mathbb{R}^{d+1} \}$ corresponding to the perceptron is $d+1$.

We need to show 
1. That there exists a data set of size d+1 that can be shattered by hyperplanes
2. That no data set of size d+2 can be shattered by hyperplanes

We will give a few more hints than the book does.
### Shattering d+1 points
As the book hints you must create an "easy" data set that you store in matrix $X$. 

**Hint:** We suggest you consider as a data matrix, the $(d+1) \times (d+1)$ matrix $X$ whose first column is all-1s (required since $\mathcal{X} = \{1\} \times \mathbb{R}^d$) and where the lower $d \times d$ corner of the matrix is the $d \times d$ identity matrix.

Show that you can construct any dichotomy $y \in \{-1,+1\}^{d+1}$ using some $h \in \mathcal{H}$ and the data matrix $X$ defined above. That is, you have to show that for any $y \in \{-1,+1\}^{d+1}$, you can find some hypothesis $w$ such that for all $i$, we have $\textrm{sign}(w^\intercal x_i)=y_i$ where $x_i$ is the $i$'th row of $X$.

### SOLUTION MATH
Given a dichotomy $y \in \{-1,+1\}^{d+1}$, we pick the hypothesis $w$ such that $w_1 = 0.1y_1$ and $w_i = y_i$ for $i>1$. Observe that for the first row of $X$ (data item $x_1$), we have $w^\intercal x_1 = w_1 = 0.1 y_1$, hence $\textrm{sign}(w^\intercal x_1) = y_1$. For $i>1$, notice that $w^\intercal x_i = w_1 + w_i = 0.1y_1 + y_i$. Since $y_1$ is multiplied by the factor $0.1$, we still have $\textrm{sign}(w^\intercal x_i) = y_i$. 

Here is a another solution. Observe that the matrix $X$ is invertible (subtract first row from the others in Gaussian elimination and get an identity matrix). Now merely set $w=X^{-1}y$ for an arbitrary dichotomy encoded by $y$. Hence $Xw = XX^{-1}y= y$. 

### END SOLUTION


### No Shattering of d+2 points.
Must show that for any d+2 points, there is a  dichotomy hyperplanes can not capture.

**Hint:**

Consider an arbitrary set of d+2 points $x_1,\dots, x_{d+2}$ of dimension (d+1) and think of them as vectors in $\{1\} \times \mathbb{R}^d \subset \mathbb{R}^{d+1}$.
Since we have more vectors than dimensions the vectors must be linearly dependent.

i.e. there is a $j$ such that:
$$
x_j = \sum_{i\neq j} a_i x_i
$$
Since $x_j$ is determined by the other data points then so is $w^\intercal x_j$ for any $w$. This means the classification on point $x_j$ is dictated by the classification of the other data points and thus cannot freely be chosen.
i.e.
$$
w^\intercal x_j = w^\intercal \sum_{i\neq j} a_i x_i =\sum_{i\neq j} a_i w^\intercal x_i
$$
Define an impossible dichotomy as follows. 
$$
y_i = \textrm{sign}(a_i), \quad i\neq j, \quad y_j = -1
$$
Show this dichotomy is impossible!

### SOLUTION MATH
We have 
$$
w^\intercal x_j =\sum_{i\neq j} a_i w^\intercal x_i
$$
Furthermore, we must have $\textrm{sign}(a_i) = y_i$ for $i \neq j$ and $\textrm{sign}(w^\intercal x_i) = y_i$ for $i \neq j$. This means that $a_i w^\intercal x_i$ is positive for $i \neq j$. Hence $w^\intercal x_j > 0$ and we cannot have $\textrm{sign}(w^\intercal x_j) = -1$.
### END SOLUTION

## BONUS Exercise If Time 7: Book Problem 2.18 In short
Define
$$
\mathcal{H}= \{h_\alpha \mid h_\alpha(x) = (-1)^{\lfloor \alpha
          x\rfloor}, \alpha \in {{\mathbb R}}\}
$$ 

Show that the VC dimension of ${{\mathcal H}}$ is infinite (even though there is only one parameter!)

Hint: Use the points set
$x_1=10,x_2=100,\dots,x_i = 10^i,\dots,x_N=10^N$ and show how to implement any dichotomy $y_1,\dots,y_N \in \{-1, +1\}^N$ (find $\alpha$ that works).
You can safely assume $\alpha >0$.


### SOLUTION MATH
Map $y$ to $\alpha$ as follows. define 
$$
f(y) = \begin{cases}
1 \textrm{ if } y = -1\\
0 \textrm{ if } y = +1
\end{cases}
$$
set $\alpha$ to the number defined by concatenating the mapped digits $0.f(y_1)f(y_2)\dots f(y_N)$
This means that for $y = [-1, +1, -1]$, $\alpha = 0.101$. Consider $h_\alpha(x_i) = (-1)^{\lfloor \alpha 10^i \rfloor}$. The multiplication by $10^i$ shifts the bit pattern in $\alpha$ by $i$ positions. The floor operation discards the decimal points. The value of $(-1)^k$ for integer $k$ is determined solely from the parity of $k$.

### END SOLUTION